"""Domain-general extraction and state-maintenance prompts."""

EXTRACTION_SYSTEM_PROMPT = """Extract conversational memory as semantic long-term memory, JSON only. Extract one claim per distinct proposition worth retaining: stable facts, observations, measurements, preferences, constraints, decisions, adopted plans, meaningful state changes, explicit statuses, significant history, and persistent relationships. Do not decompose every sentence.

Persistence describes whether a proposition is CURRENT, FORMER/BACKGROUND, or BOUNDED; it is not determined merely by past-tense wording. Use state for a currently true or ongoing fact meaningful across future conversations, even when it began long ago: "I still work at Acme" -> employer=Acme, state; "I've lived in Boston for ten years" -> lives_in=Boston, state; "I currently use Python every day" -> uses=Python, state. Use history for a former or completed background fact not asserted as current: "I worked at Acme from 2019 to 2022" -> history; "I used to live in Boston" -> history. Use episode for a bounded occurrence, action, measurement, recommendation, or transient event: "I had an interview with Acme yesterday" -> episode. Do not infer an enduring state from an event unless it is explicitly asserted.

Do not extract assistant paraphrases of an immediately preceding user fact, rhetorical or formatting requests, acknowledgements, empathy, meta-dialogue, or generic assistant reasoning, causal speculation, pedagogical explanation, or reassurance as a fact about the user. Assistant content may be retained only when it is an explicit conversation-specific decision, instruction, recommendation, diagnosis/status assertion, commitment, correction, or personalized conclusion.

Preserve scope, negation, uncertainty, quantities, modality, persistence, and temporal wording; do not add domain knowledge or infer causes/dates. Every accepted claim MUST cite one or more exact source_turn_ids from the visible turns. The subject is a person/scope, never a predicate or attribute. For example, GOOD: subject=User, subject_id=primary_user, predicate=lives_in, value=Boston; BAD: subject=lives_in, subject_id=speaker:lives_in. Use speaker:<name> only for an actual visible participant, third_party:<name> only for the supplied consultation target, and general_non_personal for generic discussion. Return {"episode_summary": str, "claims": [{"subject_id": "primary_user|general_non_personal|speaker:<name>|third_party:<name>", "subject": str, "predicate": str, "value": str, "qualifiers": object, "polarity": "positive|negative|uncertain", "modality": "asserted|observed|planned|recommended|hypothetical", "persistence": "state|episode|history", "valid_from": str|null, "valid_to": str|null, "valid_time_text": str|null, "source_turn_ids": list}]} ."""

UPDATE_SYSTEM_PROMPT = """Classify the relationship between one new conversational claim and candidates as JSON only. Use NEW, DUPLICATE, CORROBORATE, REFINE, SUPERSEDE, CONFLICT, or EPISODIC. Do not use external knowledge. SUPERSEDE requires an explicit later persistent change. CONFLICT preserves incompatible claims without a clear transition. DUPLICATE is repetition or restatement; CORROBORATE requires independent conversational evidence. Historical candidates are context only: SUPERSEDE, REFINE, and CONFLICT must target an active or contested claim.

When new_claim_source_turns and candidate_claim_source_turns are present, the claims share an episode. Classify their exact evidence as same_episode_relation: restatement, correction, state_change, refinement, contradiction, or none. A same-episode paraphrase or assistant restatement is DUPLICATE, never independent CORROBORATE. SUPERSEDE requires correction or state_change in later cited evidence. REFINE requires refinement, correction, or state_change. CONFLICT requires contradiction. Return {"matched_claim_id": str|null, "operation": str, "same_episode_relation": "restatement|correction|state_change|refinement|contradiction|none", "confidence": number, "rationale": str}."""
